
# -*- coding: utf-8 -*-
"""
Analyze scanned surveys generated by the provided ReportLab generator.

- Geometry synchronized with the generator:
  * A4 (595.2756 x 841.8898 pt), margins 10 mm
  * Fiducials: 5 mm squares at four corners
  * Part A: 3 columns (7,7,6 items), compact row spacing
  * Part B: 5 frames (26 mm height), QR placed left of frame (per generator)

- Part A detection: OpenCV (Otsu + ratio of ink in inner ROI); select max box > threshold.
- Part B OCR: pytesseract (lang='pol', --psm 6), preprocessed (denoise + Otsu).
- Excel: header A.1..A.20 + B labels; summary rows: mean/std excluding 6, and count of 6.

Usage:
    python analyze_surveys.py --input ./scans --output wyniki.xlsx
"""

import os
import sys
import argparse
from dataclasses import dataclass
from typing import List, Tuple

import numpy as np
import cv2
from PIL import Image

try:
    from pdf2image import convert_from_path
except Exception:
    convert_from_path = None

try:
    import pytesseract
except Exception:
    pytesseract = None

from openpyxl import Workbook
from openpyxl.styles import Alignment

# --- Geometry synchronized with the provided generator ---
POINTS_PER_MM = 2.83465
PAGE_W_PT = 595.275590551  # A4 width (pt)
PAGE_H_PT = 841.88976378   # A4 height (pt)

MARGIN_L_MM = 10
MARGIN_R_MM = 10
MARGIN_T_MM = 10
MARGIN_B_MM = 10

FIDUCIAL_SIZE_MM = 5          # <= generator
CHECKBOX_SIZE_MM = 5
CHECKBOX_GAP_MM = 2
COL_GAP_MM = 6                # three columns

CHECKBOX_SIZE_PT = CHECKBOX_SIZE_MM * POINTS_PER_MM
CHECKBOX_GAP_PT  = CHECKBOX_GAP_MM  * POINTS_PER_MM

CONTENT_W_PT = PAGE_W_PT - (MARGIN_L_MM + MARGIN_R_MM) * POINTS_PER_MM
COL_GAP_PT   = COL_GAP_MM   * POINTS_PER_MM

# col_width = (CONTENT_W - 2*COL_GAP)/3 - 5mm; x_fix = 5mm
COL_W_PT     = (CONTENT_W_PT - 2*COL_GAP_PT) / 3.0 - (5 * POINTS_PER_MM)
X_FIX_PT     = 5 * POINTS_PER_MM

X_LEFT_PT  = MARGIN_L_MM * POINTS_PER_MM + X_FIX_PT
X_MID_PT   = MARGIN_L_MM * POINTS_PER_MM + COL_W_PT + COL_GAP_PT + X_FIX_PT
X_RIGHT_PT = MARGIN_L_MM * POINTS_PER_MM + 2*(COL_W_PT + COL_GAP_PT) + X_FIX_PT

# Part A start in generator:
# start_y = PAGE_H - MARGIN_T - 20mm
# y = start_y - 7mm
# draw_scale_header_vertical(...); y -= 8mm  => first label baseline:
START_A_TITLE_Y_PT   = PAGE_H_PT - (MARGIN_T_MM + 20) * POINTS_PER_MM
